### PR TITLE
v0.2.1

### PR DESCRIPTION
**Pull request by davidbrochart**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by davidbrochart** [comment]
@conda-forge-admin, please rerender

**Comment by kylebarron** [comment]
Feels like whack-a-mole with failing tests 😅

**Comment by davidbrochart** [comment]
It looks like the line with `VERSION_INFO` is still there.

**Comment by kylebarron** [comment]
Yikes you're right... I do see it in the source tarball though it's gone in master: https://github.com/kylebarron/pydelatin/blob/6c60475cc78502c82cf01ac99c1525209b4bddbf/src/main.cpp#L189-L193...

Lol I'm an idiot 🙈 In the [commit log](https://github.com/kylebarron/pydelatin/commits/master) I accidentally merged master with the relevant commit _after_ pushing the new tag, so the v0.2.1 [still has it](https://github.com/kylebarron/pydelatin/blob/cafb8b62e9ecc6c9180c8f9c308ea06877f27eaf/src/main.cpp#L194-L199). Sorry about that. I'll push an 0.2.2 🤦‍♂️

**Comment by kylebarron** [comment]
I just pushed the v0.2.2 tag to Github, so the new source/wheels should be published in ~10-15 minutes

**Comment by davidbrochart** [comment]
No worries, thanks!

**Pull request closed without merging**
