### PR TITLE
Enable windows

### PR DESCRIPTION
**Pull request by davidbrochart**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by kylebarron** [comment]
🤷

**Comment by davidbrochart** [comment]
@kylebarron the error here seems to be because `hmm` doesn't include the `<algorithm>` header, but it looks like it finds `glm` (conda-forge puts the `glm` headers in the right directory which is in the search path).

**Comment by kylebarron** [comment]
Hmm is that where these errors are coming from?

```
    src/heightmap.cpp(47): error C2039: 'min': is not a member of 'std'
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\vector(20): note: see declaration of 'std'
    src/heightmap.cpp(47): error C3861: 'min': identifier not found
    src/heightmap.cpp(48): error C2039: 'max': is not a member of 'std'
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\vector(20): note: see declaration of 'std'
    src/heightmap.cpp(48): error C3861: 'max': identifier not found
```

**Comment by kylebarron** [comment]
There is an `#include <algorithm>` here:

https://github.com/kylebarron/pydelatin/blob/13884f3fdffe2341c17748572add705e70c2c7da/src/triangulator.cpp#L3

**Comment by davidbrochart** [comment]
Yes, I opened an issue in `hmm`: https://github.com/fogleman/hmm/issues/13

**Comment by davidbrochart** [comment]
> There is an `#include <algorithm>` here:
> 
> https://github.com/kylebarron/pydelatin/blob/13884f3fdffe2341c17748572add705e70c2c7da/src/triangulator.cpp#L3

It should be before `#include "triangulator.h"`.

**Comment by kylebarron** [comment]
Can you tell I don't know C++ 😅

**Comment by davidbrochart** [comment]
Actually I'm not sure of my answer! Can you try?

**Comment by davidbrochart** [comment]
@conda-forge-admin, please rerender

**Comment by kylebarron** [comment]
It's still failing with the patch?

**Comment by davidbrochart** [comment]
@conda-forge-admin, please rerender

**Comment by davidbrochart** [comment]
@conda-forge-admin, please rerender

**Comment by davidbrochart** [comment]
@kylebarron we made some progress, now the error is:
```
src/main.cpp(195): error C2143: syntax error: missing ';' before 'constant'
```
on this line:
```cpp
m.attr("__version__") = VERSION_INFO;
```

**Comment by davidbrochart** [comment]
@conda-forge-admin, please rerender

**Comment by davidbrochart** [comment]
@kylebarron I just replaced the `#ifdef` with `m.attr("__version__") = "dev";` and it works, not sure what there is in `VERSION_INFO` that Windows doesn't like. You have that in `setup.py`:
```python
ext.define_macros = [('VERSION_INFO', '"{}"'.format(self.distribution.get_version()))]
```

**Comment by kylebarron** [comment]
The `VERSION_INFO` was copied from pybind11's Windows example: https://github.com/pybind/python_example/blob/4a08067caf2fb2200a6c2106249a61d023dcf05d/src/main.cpp#L35-L39

**Comment by kylebarron** [comment]
I suppose `VERSION_INFO` isn't really important here because I have a separate Python wrapper around the Pybind11 parts. If I had no Python wrapper, figuring out the pybind11 issues would be more important.

**Comment by davidbrochart** [comment]
Sounds good, closing this PR then as we will re-enable Windows with the next PyPI release.

**Comment by kylebarron** [comment]
0.2.1 is published with the recent changes https://pypi.org/project/pydelatin/0.2.1/#files

**Pull request closed without merging**
